version: '3'
services:
  server:
    build:
      context: ./backend
    ports:
      - "8080:5000"
    environment:
      - NODE_ENV=production
      - MONGO_URL=mongodb://db:27017/area
    depends_on:
      - db
    restart: always

  client_web:
    build:
      context: ./frontend
    ports:
      - "8081:80"
    depends_on:
      - server
      # - client_mobile
    volumes:
      - shared_volume:/usr/share/nginx/html
    restart: always

  # client_mobile:
  #   build:
  #     context: ./mobile
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - server
  #   volumes:
  #     - shared_volume:/usr/share/nginx/html
  #   restart: always

  db:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data:
    driver: local
  shared_volume:
    driver: local