services:
  backend:
    build:
      context: ./backend
    container_name: backend
    depends_on:
      - mongo
    ports:
      - '8080:5000'
    environment:
      - MONGO_URI=${MONGO_URI}
      - PORT=5000

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    depends_on:
      - backend

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
      

volumes:
  mongo-data:
