name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x, 22.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Change directory to backend
        run: cd backend

      - name: Install dependencies
        run: npm install
        working-directory: backend

      - name: Run backend tests
        run: npm run test
        working-directory: backend

      - name: Upload Jest test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: jest-results
          path: backend/jest-results.xml

      - name: Upload coverage report
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: backend/coverage/
