name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Install dependencies
      run: npm install

    - name: Run tests
      env:
        NODE_ENV: test  # Set the environment to test
      run: npm run test

    - name: Upload Jest test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: jest-results
        path: jest-results.xml

    - name: Upload coverage report
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: coverage/
