name: Mirroring

on: [push, delete]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: yesolutions/mirror-action@master
      with:
        REMOTE: ${{ secrets.GIT_REMOTE_URL }}
        GIT_SSH_PRIVATE_KEY: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
        GIT_SSH_NO_VERIFY_HOST: "true"